blank_issues_enabled: false
contact_links:
  - name: GitHub Community Bug Report
    url: https://github.com/kse3hi/velocitas-docs/issues/new
    about: Prease ask and report here.
    contact_links:
